#### Using python [List of list] With Dataframe

In [1]:
import pandas as pd

In [2]:
data = [["Harry",89],["Shelu",78],["Devu",88],["Shrut",98],["Granthu",58]]

In [3]:
pd.DataFrame(data, columns=["Name","Marks"])

      Name  Marks
0    Harry     89
1    Shelu     78
2     Devu     88
3    Shrut     98
4  Granthu     58

#### Using python Dictionary  Dataframe

In [4]:
data = {
   "A" : [21,56,54],
    "B":[87,58,95]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

    A   B
0  21  87
1  56  58
2  54  95

#### Using numpy array with Dataframe

In [7]:
import numpy as np

In [8]:
arr = np.array([[2,1],[5,6]])

In [9]:
df = pd.DataFrame(arr, columns = ["A","b"])

In [10]:
df

   A  b
0  2  1
1  5  6

#### Read the Excel Sheet Data

In [16]:
df = pd.read_excel("data.xlsx")

In [17]:
df # df variable = [Dataframe]

,Actor,Film,Year,Genre,BoxOffice,IMDb,Unnamed: 6,Unnamed: 7,Unnamed: 8,Name,Age
0,Alia Bhutt,Deva,2023,Commedy,1050,7.2,NaN,NaN,NaN,Janvi,25.0
1,Sita,Ramayan,2017,Inspiration,565,6.0,NaN,NaN,NaN,Deesha,22.0
2,Mandoddari,Ramayan,2016,Inspiration,2024,8.4,NaN,NaN,NaN,Preksha,15.0
3,Ahalya,Ramayan,2022,Action,431,5.6,NaN,NaN,NaN,Binal,25.0
4,sabribai,Ramayan,2018,Action,585,7.0,NaN,NaN,NaN,Leena,65.0
5,Radha,Krishna,2005,Inspiration,111,8.3,NaN,NaN,NaN,Kashish,35.0
6,Ganga,Aeknath,1985,Inspiration,180,7.5,NaN,NaN,NaN,NaN,NaN
7,Urminla,Ramayan,1980,Action,475,5.5,NaN,NaN,NaN,NaN,NaN
8,kashlaya,Ramayan,2000,Inspiration,318,6.2,NaN,NaN,NaN,NaN,NaN

In [18]:
pd.read_csv("data1.csv")

      Film  Year        Genre  BoxOffice  IMDb
0     Deva  2023      Commedy       1050   7.2
1  Ramayan  2017  Inspiration        565   6.0
2  Ramayan  2016  Inspiration       2024   8.4
3  Ramayan  2022       Action        431   5.6
4  Ramayan  2018       Action        585   7.0
5  Krishna  2005  Inspiration        111   8.3
6  Aeknath  1985  Inspiration        180   7.5
7  Ramayan  1980       Action        475   5.5
8  Ramayan  2000  Inspiration        318   6.2